spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url:  jdbc:mysql://localhost:3306/fp_db?characterEnding=utf8&useSSL=false
  jpa:
        open-in-view: true
        hibernate:
          ddl-auto: create
          naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5Dialect
        database: mysql
  thymeleaf:
        mode: HTML
        cache: false
        servlet:
          content-type: text/html
        encoding: UTF-8